### ISSUE TITLE
Persist diagnostic_level after HVAC restart

### ISSUE THREAD

**Issue by 42Network** [PeteRager/lennoxs30#205]
### Discussed in https://github.com/PeteRager/lennoxs30/discussions/204

Per discussion thread, please add either some code to persist the diagnostic_level after Lennox system restarts, or at least mention in the integration notes that the use should be aware that diagnostic_level will need to be checked and reset occasionally to allow diagnostic data to always be available.

As you suggested, this could be a simple HA automation that would set diagnostic_level to 2 based on some trigger, such as:
1. Whenever Lennox system uptime goes backwards
2. Whenever HA sees diagnostic_level is NOT 2

<div type='discussions-op-text'>

<sup>Originally posted by **42Network** September 13, 2022</sup>
SNIP
4. Does the diag level persist across Lennox system restarts? I've had to once or twice put system_diagnostic_level back to 1 and I think that was after I had "rebooted" the Lennox system.
5. Is there a way to make the diag level permanently persistent? I.e. I always want to have heat/cool demand and CFM demand on my dashboards.
SNIP
</div>

**Comment by PeteRager** [comment]
Here’s a solution draft for review.

The existing diagnostic level number entity will be enhanced to reset the diagnostic level.

Definitions

- **Requested State** - this is the state that has been requested from home assistant by setting the number entity to a value.  On integration startup or reload the requested state will be set to the current state.
- **Current State** - this is the state in the controller.

Use Cases
1.  On a controller reset (power outage, etc.) the current state always resets to zero.  If the requested state was non zero before the outage, the requested state should be sent to the controller.
2.  Lennox technician shows up and places system into diagnostic mode, the integration should not interfere with this - for example by resetting it to zero - if that was the last state set from HA

Requirements

1. When current state changes to zero and requested state is non zero, log warning message, send requested state to S30.
2. When current state changes to non zero and requested state is zero, log info message, do nothing
3. When current state changes to non-zero and requested state is non-zero, log info message, do nothing.  For example, HA is using diag level 1 and Lennox App set to diag level 2.

There are several potential issues this could introduce. 
1. On systems that become unstable due to diagnostics, often the controller reboots and hence resets to zero, which prevents the system from being in a continuous cycle of rebooting.  By automatically forcing it back into diagnostic mode, this could cause an HVAC outage. Not sure how to differentiate periodic reboots vs periodic power outages?
2. If Home Assistant is not on a UPS, when HA restarts there is no restore state, so it will remain at zero.  My HA is on a UPS.  Should we consider this use case?

**Comment by PeteRager** [comment]
The update will have a sample automation that can be used / tailored by the end-user to automatically restore diaglevel to 2 on a controller reboot.
