### ISSUE TITLE
S40 remote sensor support

### ISSUE THREAD

**Issue by ghwong** [PeteRager/lennoxs30#228]
The current API worked and support S40 thermostat but this new Lennox thermostat has remote sensor capability.

Need help and support to add the remote sensor readings (temp, humidity, battery level, and wireless signal).
Thannks

**Comment by PeteRager** [comment]
Initial analysis of message logs shows that this data is not currently coming through on the topics the API is subscribed to.  Next step is to investigate how the new Lennox apps for the S40 obtain this information.

The new sensors appear to use BLE for their communication.

**Comment by PeteRager** [comment]
@ghwong

I updated the API so it should capture the messages from the new sensors to the message log.

Here are the steps to update on your HASS system.

Inside your config directory there is a directory custom_components/lennoxs30, in that directory there is a file called manifest.json - this file tells HASS what version of the API to download.

Change this line
```
 "requirements": ["lennoxs30api==0.2.1"],
```

to

```
 "requirements": ["lennoxs30api==0.2.2"],
```

that will cause the updated API to be installed on next restart.  If you don't feel comfortable editing the file, i can also create a new release tomorrow.

Once the change is made, do the following:
1. delete the current message log file
2. restart HASS
3. the sensors update every 2 minutes, it'd be good if we could capture some changes, open a window or something to get the temperatures to change, they are also occupancy sensors, so walk into each room that has one. Once you see some changes on the S40 panel then
4. grab the message log and post it

If our test is successful we'll have the data in the messages so that the additional sensors can be added.

Let me know if you have questions.

**Comment by ghwong** [comment]
Okay.. here is the message log. I can see the 2 sensors in the log now
[s30_local (2).log](https://github.com/PeteRager/lennoxs30/files/11238046/s30_local.2.log)

**Comment by PeteRager** [comment]
Thanks. That is helpful.  Yes, I can see both sensors with a lot of information including the initial temperature, humidity, battery level and occupancy.  The one thing I'm not seeing is messages that update these initial values.  I do see a couple of these come through

```
    "messages": [
        {
            "MessageId": 0,
            "SenderID": "**redacted**",
            "TargetID": "homeassistant",
            "MessageType": "PropertyChange",
            "Data": {
                "ble": {
                    "publisher": {
                        "publisherName": "lcc"
                    },
                    "devices": [
                        {
                            "device": {
                                "wdn": 513,
                                "rasStatus": {
                                    "isParticipating": true,
                                    "temperatureStatus": "inRange"
                                }
                            },
                            "id": 2
                        },
                        {
                            "device": {
                                "wdn": 512,
                                "rasStatus": {
                                    "isParticipating": false,
                                    "temperatureStatus": "inRange"
                                }
                            },
                            "id": 1
                        }
                    ]
                }
            }
        }
    ]
}
```

 But that is just telling us it is in range.  It's also possible it just did not send an update in your test. Based on the configuration it look like a 0.2 degree threshold on Temperature and a 1% threshold on humidity.  
 
If the log is still running upload it and/or see if there are other "ble" messages that have temperatures in them.

**Comment by ghwong** [comment]
I left it running awhile and the log size was huge.. zipped it for reference
[s30_local (3).zip](https://github.com/PeteRager/lennoxs30/files/11239753/s30_local.3.zip)

**Comment by PeteRager** [comment]
Excellent that's exactly what we needed. 

I have what I need for now. Probably take a week or two to get the new release ready. I'll post progress in this issue.

This is what I propose?

Create a device for each remote sensor with appropriate attributes
Create sensors for each device
- Temperature
- Humidity
- Battery %
- Signal Strength (RSSI)
- Occupancy

In the dataset they have 3 values for temperature - "RAS Analog Temp", "RAS Digital Temp" and ""RAS Tsense" - which all have different values.  I believe the right value is "RAS Tsense" but not 100% on that, we'll test that when the beta is ready.

Yes, message logging can chew up alot of space, you may want to go into the integration configuration and disable it for now.  You'll need to restart HASS for it to take effect.

**Comment by ghwong** [comment]
I'm good with the plan.
We can confirm the temperature value with what I see from app once this is ready for beta testing.

I disabled the message logging for now till we need any further data from it.

**Comment by PeteRager** [comment]
The new release is available here:

https://github.com/PeteRager/lennoxs30/releases/tag/2023.4.0

Or update from HACS.  Documentation is here:

https://github.com/PeteRager/lennoxs30/tree/2023.4.0#s40-remote-sensors

A couple of details:

You should see two new devices created for your remote sensors "Master Bedroom" and "Basement" they should have a collection of entities and diagnostic entities.

I added all 3 temperature sensors - Analog Temperature, Digital Temperature and Temperature.  I believe the last one is what Lennox is showing.  In your message logs Analog Temperature appears to have the same value as Temperature; while Digital Temperature has a different value and it typically higher.  Please validate which one of these corresponds to what you see in the Lennox App and Panel?

On the occupancy sensor, I had to guess that a "1" means occupied.  Please see if the state is reporting correctly or if it is backwards.

If the device is turned off, the comm status entry should report "disconnected".  I don't know if there is way to turn off one of the sensors?  I also don't know how long it will take for it to detect.  When it is detected all of the other sensors on the device should go unavailable.  If this is something you can test - fantastic, otherwise no worries.

There are two binary_sensors called "Device Status" and "Alarm Status", I have no idea what these represent. If you do let me know.

**Comment by ghwong** [comment]
Hello, I just managed to download new version thru HACS and it is not working.
Seem to be some error and fault on it.
I reverted to the older version and ran fine again.
Let me load the new version and collect log again in awhile

**Comment by PeteRager** [comment]
Ok, I must have missed something.  If there are errors in the home-assistant.log please send those.

**Comment by ghwong** [comment]
Here is the error after upgrading to the new version
![image](https://user-images.githubusercontent.com/10466928/234130526-05a32d54-7e28-4332-aab1-ce027e6030f6.png)

![image](https://user-images.githubusercontent.com/10466928/234130627-9ae0447d-97cb-41a9-9b77-3ddfab7ae425.png)
[home-assistant.log](https://github.com/PeteRager/lennoxs30/files/11315098/home-assistant.log)

**Comment by PeteRager** [comment]
What version of home assistant are you running?

**Comment by ghwong** [comment]
Opps.. I'm running 2022.12.8 is it too old? I might have overlook the min requirement

**Comment by PeteRager** [comment]
Yes, that is the issue, those news constant were introduced in November and integration developers were requested to migrate.  Unfortunately, that makes the release no longer compatible with 2022.12.8.  Apologies.

Well either need to have you upgrade or I can try to remove those changes or if you don't want to upgrade now when you do later on you can test the remote sensors.

**Comment by ghwong** [comment]
Let me do the upgrade instead. Overdue for me to update my HASS for awhile. I will let you know again on the testing later
Thanks

**Comment by PeteRager** [comment]
Sounds good,  I'm still running 2022.12.7 for my home system also and need to upgrade.

**Comment by ghwong** [comment]
Upgraded my HA and it is working fine now
Added the screenshot of the sensors.

From what I interpret, digital temp seem to be the average of my thermostat and all other sensors temp while analog and the temp is the sensor temperature. I will start trending the sensor to be sure.

![image](https://user-images.githubusercontent.com/10466928/234135846-537cd786-3778-418b-b17b-8f148326e577.png)

**Comment by PeteRager** [comment]
Very cool.  Great to see that it is working!

**Comment by ghwong** [comment]
Thanks again for the help! Glad to see that this work for the remote sensors too.

Capturing the snapshot of all the temps.. I'm at lost as well but will monitor how there work later
![image](https://user-images.githubusercontent.com/10466928/234136740-595d1d3f-1e4e-454f-b35a-02776c0b1897.png)

**Comment by PeteRager** [comment]
Thanks for helping me get the integration supporting the S40.  As you find out information please post it in the discussion or open issues so we can get the documentation more accurate.
