### ISSUE TITLE
Integration Stops Functioning S40 Thermostats

### ISSUE THREAD

**Issue by julietalpha1** [PeteRager/lennoxs30#245]
**Describe the bug**
Yesterday I noticed my values on HA were not available for both my S40 thermostats.  I restarted HA and no change.  I manually rebooted both thermostats and the integration started working again.  This evening I had the same problem.   
Thermostats are running Software 04.20.0107

The logs are below:

Logger: custom_components.lennoxs30
Source: custom_components/lennoxs30/__init__.py:356
Integration: Lennox S30/E30 ([documentation](https://github.com/PeteRager/lennoxs30/blob/master/README.MD), [issues](https://github.com/PeteRager/lennoxs30/issues))
First occurred: 8:42:01 PM (2 occurrences)
Last logged: 8:42:02 PM

async_setup unexpected error login failed due to client response error [https://192.168.10.61/Endpoints/ha_s40_down/Connect] ClientResponseError Error while executing request: [Content-Length can't be present with Transfer-Encoding]: error=<class 'aiohttp.client_exceptions.ClientResponseError'>, resp.status=[400], resp.request_info=[RequestInfo(url=URL('https://192.168.10.61/Endpoints/ha_s40_down/Connect'), method='POST', headers=<CIMultiDictProxy('Host': '192.168.10.61', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.11 aiohttp/3.8.4', 'Content-Length': '0', 'Content-Type': 'application/octet-stream')>, real_url=URL('https://192.168.10.61/Endpoints/ha_s40_down/Connect'))], resp.headers=[None]
async_setup unexpected error login failed due to client response error [https://192.168.10.62/Endpoints/ha_s40_up/Connect] ClientResponseError Error while executing request: [Content-Length can't be present with Transfer-Encoding]: error=<class 'aiohttp.client_exceptions.ClientResponseError'>, resp.status=[400], resp.request_info=[RequestInfo(url=URL('https://192.168.10.62/Endpoints/ha_s40_up/Connect'), method='POST', headers=<CIMultiDictProxy('Host': '192.168.10.62', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.11 aiohttp/3.8.4', 'Content-Length': '0', 'Content-Type': 'application/octet-stream')>, real_url=URL('https://192.168.10.62/Endpoints/ha_s40_up/Connect'))], resp.headers=[None]

**Version**
 - Home Assistant: 2023.6.1
 - This Integration: 2023.5.2
 

**Integration Configuration **
- Cloud or Local Connection: Local
- Inverter or Sensor Diagnostics Enabled: No

**Additional context**

**Comment by PeteRager** [comment]
Thanks for the note.

The last time this issue was seen was here
https://github.com/PeteRager/lennoxs30/issues/133

The root cause was diagnostic level not being set the zero.

Are you using diagnostics?

**Comment by julietalpha1** [comment]
I am not using diagnostics as they didn't ever seem to return any values with the S40.  I noticed things stopped working this weekend.

**Comment by PeteRager** [comment]
When you start the integration are there any warnings in the Log?

When did you upgrade to 2023.6.1? 
What HASS version were you running before?  
Had the S40 connection be stable in the past?

trying to understand if it had ever worked reliably and this is a new issue.

Are you using the power inverter option?

Have you tried restarting the smarthub?

Is your system connected to the Lennox Cloud?  Are you using the app on your phone?

I'd also try looking at the WiFi signal strength.  Have you had problems with your internet connection?

**Comment by PeteRager** [comment]
I ran a test on 2023.6.1 and it works for me on an S30.

**Comment by julietalpha1** [comment]
> When you start the integration are there any warnings in the Log?
If I restart both S40s first, there are no errors.  After a few hours (the last time it worked for about 7 hours) the errors that I posted above show up.  Restarting the integration (or HA) has no effect.  The only way to fix at that point is a restart of the S40s.
> 
> When did you upgrade to 2023.6.1? What HASS version were you running before? Had the S40 connection be stable in the past?  I upgraded to 2023.6.1 the first week of June.  (Unfortunately in my attempts to fix this I dumped the logs that show exactly when I did it).  
> 
> trying to understand if it had ever worked reliably and this is a new issue.
The integration was rock solid until 6/11.  
> 
> Are you using the power inverter option?
No
> 
> Have you tried restarting the smarthub?
With the S40s there is no separate "smart hub".  Only a reboot of each S40 resolves the issue, and then only for a couple of hours.
> 
> Is your system connected to the Lennox Cloud? Are you using the app on your phone?
Yes the system is connected to the cloud.  The phone app always works.  The integration is NOT using the cloud, but the local connection.  If I try to set up with the cloud it does not work at all.  (Limitation of the S40 on the integration?)
> 
> I'd also try looking at the WiFi signal strength. Have you had problems with your internet connection?
Wifi strength is very good - each device is within 10 feet of an access point.

Besides the supervisor version (which is now 2023.6.2), I'm wondering if the thermostats themselves get a software update.  They are now running 4.20.0107 however, I don't know what they were running (if it was different) before.

**Comment by PeteRager** [comment]
Thanks the info, yes it sounds like it's broken :-(.

From what I know, the error you are seeing indicates that the network stack inside the S40 is in a failed state; that is why it never recovers until you restart the S40.  Yes, the thermostat may automatically update its firmware.  There should be a setting on the thermostat to turn auto-updates on / off.  The recommendation in the docs for this integration is to turn that off.  I have mine off, since it is working fine for me on the S30. 

We need to determine what is causing your S40 to become unstable when the integration is talking to it.  Their are other people using the integration with S40s successfully, so we should be able to get this solved.  I'm not surprised that the cloud connection does not work, the S40 has a different phone app than the S30, I'm sure we could get it to work, but let's see if we can get the local connection stable first?

On the S30 system there is a smart hub which is located at the HVAC system. This is where the WIFI connection originates and the thermostats are connected to it with a cable. Sounds like for the S40 they got rid of that smart hub which makes sense since the HVAC equipment is usually located along way from the WIFI.  Anyways...

How is your system setup?  You have 2 S40's talking to what (heatpump, furnance, etc.)?  Is this a new install of a Lennox System or a retrofit?  Does each thermostat have a ip address? Or is there just one that is shared across them?  Is it a multi-zoned system or two completely independent systems.  If the former there should be one copy of the integration running, if the latter you'd need two copies of the integration running.  The S40s do talk to each other and forward messages back and forth, so it is possible that some type of message looping starts occurring which is taking them down.  If this is the case I'd start with deleting one of the integrations, shutting down HASS, restarting both thermos and see if we can get it stable with a single connection.

We should also enable message logging so we can see if any information is coming through. See how to enable message logging here:
https://github.com/PeteRager/lennoxs30#reporting-bugs

You can post the file here, or post a drop-box  or other storage link, or i can give you an email address.

Also there should be additional errors and warnings in the log when the failure occurs.  The error message you posted is from when you re-started the integration when it was failed.  I'd like to see what errors occur when it starts to fail after it's been running succesfully.

Two other things to try:
- change the appi_ids - sometimes this fixes strange behavior - it is possible that having two _ in the app_id causes some issue
- increase the message scan interval

**Comment by GabeDeBacker** [comment]
Hello everyone! Sorry for jumping into this, but perhaps I can provide a little more information as well. I've been looking at the code in this repository as a reference and using "PostMan" to talk to the 3 S40 Thermostats that were just installed.

What I am seeing with PostMan is that the techniques in this repo work fine UNTIL a Endpoints/<appid>/Disconnect is issued.  The S40 returns a malformed HTTP response, and then the S40 will not accept any new connections until the S40 is restarted regardless of appID.

Excerpts from Postman:
POST https://192.168.50.205/Endpoints/<appId>/Disconnect
Error: Parse Error: Expected HTTP/

POST https://192.168.50.205/Endpoints/<appId>/Connect

{"code":4,"message":"Connect Failed!: Tstat is already connected with other mobile"}

POST https://192.168.50.205/Endpoints/<differentAppId>/Connect

{"code":4,"message":"Connect Failed!: Tstat is already connected with other mobile"}

Let me know how I can help!

**Comment by GabeDeBacker** [comment]
@PeteRager  - to clarify. Yes. I am using the URLs you mentioned above. Looks like GitHub didn't like my use of greater than, less than symbols :) I'm going to restart my thermo and reproduce the scenario again at let you know what I find.

**Comment by GabeDeBacker** [comment]
Here's the raw data from PostMan for a connect, disconnect, connect sequence using the same AppID:

POST https://192.168.50.205/Endpoints/Arzel/Connect
204
82 ms
Warning: Self signed certificate
POST /Endpoints/Arzel/Connect HTTP/1.1
User-Agent: PostmanRuntime/7.32.3
 
HTTP/1.1 204 No Content
Server: MicroRelayServer-LCC
Connection: Keep-Alive
Content-Type: text/plain
z-conn_id: 0xb1e47484
z-method: POST
z-uri: /Endpoints/Arzel/Connect
z-time: Jun 21 16:52:41
Content-Length: 0
 
POST https://192.168.50.205/Endpoints/Arzel/Disconnect
204
94 ms
Warning: Self signed certificate
POST /Endpoints/Arzel/Disconnect HTTP/1.1
User-Agent: PostmanRuntime/7.32.3
Accept: */*
Accept-Encoding: gzip, deflate, br
Content-Length: 0
 
HTTP/1.1 204 No Content
Server: MicroRelayServer-LCC
Connection: Keep-Alive
Content-Type: text/plain
z-conn_id: 0xb1e47404
z-method: POST
z-uri: /Endpoints/Arzel/Disconnect
z-time: Jun 21 16:53:01
Content-Length: 0

POST https://192.168.50.205/Endpoints/Arzel/Connect
400
68 ms
Warning: Self signed certificate
POST /Endpoints/Arzel/Connect HTTP/1.1
User-Agent: PostmanRuntime/7.32.3
 
HTTP/1.1 400 Bad Request
Server: MicroRelayServer-LCC
Connection: Keep-Alive
Content-Type: text/plain
Content-Length: 84
Transfer-Encoding: chunked
 
{"code":4,"message":"Connect Failed!: Tstat is already connected with other mobile"}

Trying any other connect with any other appID fails with the same message as above. Any subsequent disconnects result in an response that isn't even HTTP :(

POST https://192.168.50.205/Endpoints/Arzel/Disconnect
Error: Parse Error: Expected HTTP/
Request Headers
User-Agent: PostmanRuntime/7.32.3
Accept: */*
Accept-Encoding: gzip, deflate, br
Content-Length: 0

**Comment by PeteRager** [comment]
@GabeDeBacker - let's move this discussion to here https://github.com/PeteRager/lennoxs30/issues/246 - as I'm not sure this is the issue that is affecting @julietalpha1

**Comment by PeteRager** [comment]
It looks like the issue reported by @GabeDeBacker may be the root cause of your issue.  We have another report in #246 from a HASS user experiencing this whenever HASS is restarted or the integration reloaded.  I do wonder if that was your issue - restarting HASS?

it seems to have been introduced in the Lennox firmware update 4.20.0107 that you reported.

I will have a new release tomorrow.  Or you can apply the manual fix in #246.

**Comment by PeteRager** [comment]
Do you have the Android or IOS App?  When they are on the local network they talk directly to the s30/s40 via the same port this integration targets.  AFAIK, that app uses the disconnect endpoint also.   If you have the app it may be a good test to try it then logout of the app, see if that crashes the thermo also?

**Comment by 42Network** [comment]
> It looks like the issue reported by @GabeDeBacker may be the root cause of your issue. We have another report in #246 from a HASS user experiencing this whenever HASS is restarted or the integration reloaded. I do wonder if that was your issue - restarting HASS?
> 
> it seems to have been introduced in the Lennox firmware update 4.20.0107 that you reported.
> 
> I will have a new release tomorrow. Or you can apply the manual fix in #246.

I am having this problem also, with a single S40 that has the latest firmware on it. I already applied the manual #246 fix and have restarted HA many times, reinstalled the Lennox HA integration many times, and restarted the S40 many times. I can get HA to see the IP address of the S40, but it never discovers any additional entities. 

How to best troubleshoot? Should I open a new Issue thread and post some log file contents?

My S40 was actually working with HA a few days ago. But in the interim two things probably happened, one of which (or both? or neither?) caused the integration to fail. Yesterday I re-connected the iHarmony zone controller, which had been enabled for a long time with my older S30, but the S30 got swapped out for an S40 a few weeks ago and only just now did the zone controller get re-connected. Also, it is possible the new version of S40 firmware got pushed out very recently.

Thanks!

**Comment by PeteRager** [comment]
@42Network - best thing to do is to enable message logging as described here and reload the integration.  

https://github.com/PeteRager/lennoxs30#reporting-bugs

Also please include any errors or warnings that are reported in the home-assistant.log

since your symptoms are different let's put all of this in a new issue?

**Comment by PeteRager** [comment]
This issue should be fixed by this update.  If not please re-open this issue.

https://github.com/PeteRager/lennoxs30/releases/tag/2023.6.1
