### ISSUE TITLE
S40 Found but Not Connect

### ISSUE THREAD

**Issue by zachgoold** [PeteRager/lennoxs30#253]
**Describe the bug**
I have tried a few times now, but haven't been able to get a device or entity after getting through the configuration screens. I can ping the device from HASS and the configuration seems to find it fine as it gets to the advanced configuration.

**To Reproduce**
Add S40 via HASS -> type in the IP -> takes you to advanced configuration -> No devices are ever created.

**Expected behavior**

**Screenshots/Logs**
![Screenshot 2023-08-05 172550](https://github.com/PeteRager/lennoxs30/assets/50751647/59991978-505f-4731-96d6-1fee80508111)

**Version**
 - Home Assistant: 
 Home Assistant 2023.8.1
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

 - This Integration:
 2023.6.1

**Integration Configuration **
- Cloud or Local Connection: Local (tried cloud as well)
- Inverter or Sensor Diagnostics Enabled: NA

**Additional context**
NA

**Comment by PeteRager** [comment]
Are there any errors/warnings  in the home-assistant.log. If so please post here.

If not please configure message logging, restart HASS, and then post the message log here.

Instructions for enabling message logging are here:
https://github.com/PeteRager/lennoxs30#reporting-bugs

**Comment by zachgoold** [comment]
The message log looks to be empty: 
![image](https://github.com/PeteRager/lennoxs30/assets/50751647/6549f697-98c0-4bcf-be8a-a82906beccd3)

It was already enabled, but I checked the settings again and restarted, still nothing.
![image](https://github.com/PeteRager/lennoxs30/assets/50751647/4267b939-c716-4fe1-bdd4-165ba5dfeb31)

home-assistant.log:
[HASS Lennox s40 Log.txt](https://github.com/PeteRager/lennoxs30/files/12270483/HASS.Lennox.s40.Log.txt)

**Comment by PeteRager** [comment]
You need to reboot the S40 and that issue should go away.

1. Stop HASS
2. Restart the S40 from the panel
3. Start HASS

That S40 may have gotten in that state if at one point you were using an earlier version of the integration.

**Comment by zachgoold** [comment]
What do you know, that worked!

I hadn't used any different versions and this is the first time setting it
up.

Thanks for the assistance!

**Comment by PeteRager** [comment]
Glad it's working now. Let me know if it happens again. Had you been using their mobile app?

I tested the message logging and it seems to be working fine for me on 2023.8.1; but I'm running in docker, so it could be specific to HASS OS.

**Comment by zachgoold** [comment]
I have only gotten the mobile app to work. No website. Sounds like it may
be a HASS issue.

**Comment by gdoerr** [comment]
I'm incredibly happy I found this! I have an S40 and was pulling my hair out. @PeteRager might I recommend a note in the README specifically about the S40. I was ready to give up until, in my desperation, I looked at the closed issues. 

I'm happy to edit and do a PR if you'd like

**Comment by zachgoold** [comment]
Just note it may fail again. Mine is currently showing unavailable after
about 24 hours of working.

On vacation so I can't troubleshoot, but plan to when I get back.

**Comment by julietalpha1** [comment]
Something I have noticed - If HA (or the integration itself) is restarted it will typically fail to reconnect to the S40s.  You have to then restart the Thermostats (directly on the panel) before it will start working again.  

It is annoying because any time you need to restart/reload HA there is a high likelihood you need to restart your thermostats.  If you aren't physically there, you have a problem.

**Comment by gdoerr** [comment]
Thanks for the feedback. As a precaution, I blocked internet access for the thermostat (and I deleted the iComfort app from my phone!). I'll report back over the next few days

**Comment by 42Network** [comment]
> Something I have noticed - If HA (or the integration itself) is restarted it will typically fail to reconnect to the S40s. You have to then restart the Thermostats (directly on the panel) before it will start working again.
> 
> It is annoying because any time you need to restart/reload HA there is a high likelihood you need to restart your thermostats. If you aren't physically there, you have a problem.

I agree this is annoying, but doesn't happen consistently for me at every HA restart. I wish I knew what situations require thermostat restart. Last time it happened I was away from home and was relying on HA to cool my house down prior to our arrival. But while I was away, I was using Nabu Casa to remotely fiddle with some other HA settings which required an HA restart, but after that restart, the Lennox integration said all entities were unavailable. 

I had to comment to my router remotely to disable the FW block rules and then used the native Lennox app to cool my house down. It seemed very strange that HA integration failed but the native Lennox app still worked. 

I am seriously going to add an inline "smart switch" to allow remote rebooting of either the thermostat or the furnace itself in the event this happens again.

-Nathan

**Comment by PeteRager** [comment]
Yes, having an article around this error would be helpful and having it linked in the readme would be good. Also we should update the error message to include a link to the article. If equipment parameters are enabled there is a button entity that will restart the smarthub - but if the S40 is disconnected the entity will be disabled - however if the command could be sent it would likely work.  I put that in after my S30 got in a failure mode while I was away on vacation - and can use if via a convoluted process using the cloud connection (disable firewall, fire up a HASS instance with a cloud connection, issue the command). Anyways a simpler way to be able to invoke the service call regardless of connection state would be beneficial.

There are two ways that I have seen this error manifest.

1.  With equipment diagnostics enabled and the S30/S40 having internet access - as all that high speed diag data gets sent to the cloud and out to any mobile devices when you activate the app - so too much data in too small of a pipe and the system backs up and enters a failure mode.
2. When the integration reconnects and someone else has called the disconnect method.  Initially this integration would call that method whenever it would log out,  now it only does this for S30s. That said, to develop this integration we monitored what the mobile app was doing and it would do the disconnect.  So it is possible that the mobile app is still doing this. I think Lennox released a bug by mistake.  Their device sends error logs to their cloud server - so they may be aware of it and may fix it in new release.

@zachgoold - it'd be good to look at the error log to see what the first error was that caused the data to go unavailable, as it sounds like this did not occur on a HASS restart? Also whether you've been using the mobile app and if you can still use the mobile app when it's in this state.

@julietalpha1 - your symptom seems consistent with item 2 above as it occurs on restart.  Do you use the mobile app? If so, perhaps try testing some scenarios of restarting HASS after using or not using the mobile app?

This issue is specific to the S40 and started appearing after their April firmware update.

**Comment by gdoerr** [comment]
Roughly one day in and it's all still working. I do have diagnostics enabled and internet access is blocked at my firewall.

I'll take a stab at an updated doc. I'm happy to look at the code changes but I'm going to physically away from the thermostat until October so I won't be able to do any testing until then.

**Comment by PeteRager** [comment]
> > Something I have noticed - If HA (or the integration itself) is restarted it will typically fail to reconnect to the S40s. You have to then restart the Thermostats (directly on the panel) before it will start working again.
> > It is annoying because any time you need to restart/reload HA there is a high likelihood you need to restart your thermostats. If you aren't physically there, you have a problem.
> 
> I agree this is annoying, but doesn't happen consistently for me at every HA restart. I wish I knew what situations require thermostat restart. Last time it happened I was away from home and was relying on HA to cool my house down prior to our arrival. But while I was away, I was using Nabu Casa to remotely fiddle with some other HA settings which required an HA restart, but after that restart, the Lennox integration said all entities were unavailable.
> 
> I had to connect to my router remotely to disable the FW block rules and then used the native Lennox app to cool my house down. It seemed very strange that HA integration failed but the native Lennox app still worked.
> 
> 
> -Nathan

Yes, that is not optimal for sure.  I don't have an S40 and not sure of what causes this situation.   


Let me see if I can get the service call to reset it coded up - and since this occurs for you regularly then we can see if it works when the S40 is in that situation?

The Lennox app uses a number of different communication modes. When going through the cloud it communicates directly through the pipe the thermostat has open. When it runs locally in your LAN it goes direct using the HTTP API, I suspect that running it locally may cause this situation to occur.  Since it only manifests on a HASS reboot or integration reload - the app could have been used a week ago.

**Comment by julietalpha1** [comment]
> @julietalpha1 - your symptom seems consistent with item 2 above as it occurs on restart. Do you use the mobile app? If so, perhaps try testing some scenarios of restarting HASS after using or not using the mobile app?

I use the mobile app, but infrequently.  I also have not been able to pinpoint when a restart of HA will cause the problem but I can try to see if there is correlation with using the Lennox mobile app or not.  

If there was some sort of service call to remotely restart the thermostats that would help - but, if the integration can't connect to them, wouldn't that prevent it from making said call?

**Comment by PeteRager** [comment]
Here is how to create a sensor in HASS to detect if the S40 has entered the bad state.  This should help as we try to detect when and why this happens.  I have this running on my S30 and will let it run overnite.

```
sensor:
  - platform: command_line
    command: "curl -k --connect-timeout 10 -m 2.0 -s -o /dev/null -w '%{http_code}' -X POST https://192.168.20.103/Endpoints/ha_rest/Connect || true "
    name: lennox_connect
    scan_interval: 60
```

Replace 192.168.20.103 with the ip address of your s40.  If you have multiple S40s you can replicate this - just give them different names.

This should have a value of 204 (which is the http code for Success with No Content) - so you can view in on your screen and/or set up an alert to notify you when it's no longer 204.

![lennox204](https://github.com/PeteRager/lennoxs30/assets/76050312/795e6907-3a76-4cba-af63-287b25d95442)

Next step, is i'll work to create an equivalent command to restart the S40 - so we can test to see if that can restart the S40 when it enters this state.

**Comment by PeteRager** [comment]
Here is the command to send to restart the smart controller.  I'm not able to test this as I'm away from my S30 and don't want to try it if I don't have local access to power cycle it.  I'm posting this if someone else with some command line and curl skills wants to give it a try:

The message body is:
```
{
    "MessageType":"Command",
    "SenderID":"ha_test",
    "MessageID":"00000000-0000-0000-0000-000000010000",
    "TargetID":"LCC",
    "AdditionalParameters":"\/resetLcc",
    "Data": {
        "resetLcc": {
            "state":"reset"
        }
    }
}
```

The URL to post it to is:

```
https://{self.ip}/Messages/Publish
```

So if you can put the body in a file, called reset.json, then the curl command would be something like this:

```
curl -k --data "@./reset.json" --connect-timeout 10 -X POST https://192.168.2.103/Messages/Publish
```

**Comment by 42Network** [comment]
The sensor gives an error for my S40:
```
curl -k --connect-timeout 10 -m 2.0 -s  -X POST https://10.1.1.120/Endpoints/ha_rest/Connect 
{"code":4,"message":"Connect Failed!: Tstat is already connected with other mobile"}%
```

**Comment by PeteRager** [comment]
> The sensor gives an error for my S40:
> 
> ```
> curl -k --connect-timeout 10 -m 2.0 -s  -X POST https://10.1.1.120/Endpoints/ha_rest/Connect 
> {"code":4,"message":"Connect Failed!: Tstat is already connected with other mobile"}%
> ```

That is interesting.  I recall that error being reported by another user here https://github.com/PeteRager/lennoxs30/issues/245#issuecomment-1599328770

Based on his analysis this looks like the start of the failure mode.  Try to reload the HASS integration, be good to know if it can reconnect in this state.  If it can then reboot the thermo (and I suppose if it can't you'll need to reboot it also), wait for HASS to reconnect and be happy, then see if the curl works.

**Comment by 42Network** [comment]
The sensor.lennox_connect seems to work much better when I use my actual App_ID of "homeassistant" as set in my Lennox configuration, rather than "ha_rest" as stated in your sensor config snippet. I assume it is correct that I should substitute my own App_ID along with my thermo IP address in your example sensor YAML? Your thermostat restart curl command worked also, but as you suspected I had to put my App_ID of "homeassistant" into the payload.

Not sure what this next test means, but if I put in some random string for the App_ID, I get the same "already connected" error as above even though there is clearly not such a session. If I then use the correct App_ID, I get the expected 204.

```
% curl -k --connect-timeout 10 -m 2.0 -s  -w '%{http_code}' -X POST https://10.1.1.120/Endpoints/ha_rest_fooadsfadsfasdfasdf/Connect
{"code":4,"message":"Connect Failed!: Tstat is already connected with other mobile"}400% 

% curl -k --connect-timeout 10 -m 2.0 -s  -w '%{http_code}' -X POST https://10.1.1.120/Endpoints/homeassistant/Connect              
204%                     
```

**Comment by PeteRager** [comment]
Thank you @42Network that is really good information.  On the S30 I do not have to use the same App ID as the integration for the curl command. I also have a second integration running on my test system.  So that is 3 unique connections.  It looks like on the S40 they are now limiting that to 1 active connection.  Also good to know the reset command does work.  

I'd really like to make sure that unloading / reloading the integration is not causing the failure.  When you have time, let's try reloading the integration a bunch of times.  Reload; wait a minute - verify data is coming in and CURL is still at 204; repeat.  Do that 5-10x?

On my system I've been running then curl command overnight using a different app Id. Everything is still functioning - 2 integrations (test and prod) and the curl.  However, it is causing a set of transient communication errors, that the integration recovers from w/o making the data unavailable.   I'm going to change the curl to use the same App ID and see if this goes away. 

![IMG_3059](https://github.com/PeteRager/lennoxs30/assets/76050312/ddca44b7-798e-475a-854f-1c44430eadda)

Looks like timeout and client errors which I don't have showing in that dashboard.  

![IMG_3060](https://github.com/PeteRager/lennoxs30/assets/76050312/152e0596-718b-45b6-a581-1ad3e6037fbf)


```
      - type: grid
        columns: 3
        square: false
        title: Communications
        cards:
          - type: entity
            entity: lennoxs30.state
          - type: entity
            entity: lennoxs30.state
            attribute: receive_count
            name: Receive Count
          - type: entity
            entity: lennoxs30.state
            attribute: message_count
            name: Message Count
          - type: entity
            entity: lennoxs30.state
            attribute: http_4xx_cnt
            name: http_4xx
          - type: entity
            entity: lennoxs30.state
            attribute: http_5xx_cnt
            name: http_5xx
          - type: entity
            entity: lennoxs30.state
            attribute: last_receive_time
            name: last_receive
          - type: entity
            entity: lennoxs30.state
            attribute: last_error_time
            name: last_error
          - type: entity
            entity: lennoxs30.state
            attribute: last_reconnect_time
            name: Last Reconnect
          - type: entity
            entity: lennoxs30.state
            attribute: error_count
            name: Error Count
```

**Comment by 42Network** [comment]
Here is an update. My S40 integration survived multiple (about 10) reloads of the integration. The curl command always returned 204. However, it did NOT survive an HA restart. All S40 entities were unavailable. The curl command also failed, even when using my correct App_id of "homeassistant" - in fact, no matter which App_id I used, curl returned 400. However, during this time, the official Lennox app could still see my thermostat. I realize now I never re-enabled my FW block rule after my travels a few weeks ago, so perhaps that is introducing an unexpected variable into our troubleshooting.

And even after I thought the reset curl command worked yesterday, today it did not work. No matter which App_id I put in the json payload, the response was "Publish: no active connection [xyz]" where for xyz I tried both "homeassistant" and "ha_rest".

Of course, after I used the settings menu on the S40 to restart it, HA and Lennox integration are working again, including the curl command and the native Lennox app.

Got any more ideas for me to try? What do we know about available REST API endpoints on the thermostats? Is there a GET command to list the current active connections, for example? I know how to use Postman - do you have a collection of requests that work?

Thanks/Nathan

**Comment by PeteRager** [comment]
That is very interesting the messages sent on restart and reload should be identical.  The only difference is timing, a reload happens quickly while a HASS restart takes longer (that or there is a bug in the code which I'll look at today)

If you turn debug logging on, we should see a message saying

                _LOGGER.debug("Skipping logout for S40 thermostat")

We should see that both on integration reload and on HASS restart.  After a HASS restart it will be in the .1 log file.  If we do see it. then the problem appears to be related to connection inactivity when performing a HASS restart.

I had a postman collection but I lost it...probably need to try to recreate the URLs are in the API code lennoxs30api

What error was logged by the integration when it failed on restart?

If it is timing related we may find that it is ok on some restarts (as restarts seems to take longer or shorter sometimes) and not ok on others.  So we may want to stop HASS for 1 minute, restart and see what that threshold is.

**Comment by 42Network** [comment]
I will enable the debug log and look for the "logout for S40 message" shortly.

In the meantime, here are some other clues for you. Did you know that for the S40 Lennox released both a new enduser iOS app and a new tech app? I have both installed on my iPhone. Do you know how I can tell if the Lennox app is connected using local DDS or cloud API? 

Right after the tech provisioned my new S40 I was able to use the tech app myself to check things out, but ever since I enabled HA integration to the S40, the new Lennox tech app has not been able to reconnect, even though my iPhone is able to join the temporary WiFi AP generated by the S40. Also, I had no idea they were trying to use Bluetooth on the S40. Is there some side-effect of your Lennox HA integration that could be causing the new tech app to fail? I don't really care about the tech app, but it could be a clue....

**Comment by 42Network** [comment]
I enabled debug logging and I do see the messages about S40 logout.

Related to my other discussion thread, I still see the Lennox integration trying to deal with my now totally non-existent remote temperature sensors. Do you think they have anything to do with HA restart issues?

Also, you had asked what errors there were on HA restart. Here it is:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/lennoxs30/__init__.py:929 
Integration: Lennox S30/E30 (documentation, issues) 
First occurred: 12:10:58 AM (1 occurrences) 
Last logged: 12:10:58 AM

Error setting up entry 10.1.1.120 for lennoxs30
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lennoxs30/__init__.py", line 344, in async_setup_entry
    await manager.s30_initialize()
  File "/config/custom_components/lennoxs30/__init__.py", line 540, in s30_initialize
    await self.configuration_initialization()
  File "/config/custom_components/lennoxs30/__init__.py", line 736, in configuration_initialization
    got_message = await self.messagePump()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lennoxs30/__init__.py", line 929, in messagePump
    received = await self.api.messagePump()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lennoxs30api/s30api_async.py", line 688, in messagePump
    resp = await self.get(url, headers=headers, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/lennoxs30api/s30api_async.py", line 479, in get
    resp = await self._session.get(url, headers=headers, params=params, ssl=self.ssl)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError: Global task timeout

```

**Comment by PeteRager** [comment]
Regarding the tech app, it definitely uses the REST API, it connects with an App Id that is the same as the temporary network Id.  But since subsequent calls to "connect" fail in your curl test, I would not expect the tech app to be able to connect either.  If you stop the integration, restart the S40, I would think the tech app would work. I had that app running on my S30 by setting up a second wireless network with the SSID it was expecting and then running it through a BURP proxy so I could capture all the traffic.

**Comment by PeteRager** [comment]
The error you are seeing appear to be a timeout reading messages.  This is different than the Connect error we had been seeing - which means the connect was successful.  Were you running the Curl command line sensor? I wonder if having that running with the same app_id is causing issues with pending tasks waiting for messages.

**Comment by 42Network** [comment]
Yes, I had your command-line sensor running continuously since it is in my configuration.yaml. But just now I commented it out, restarted HA, and Lennox integration failed to start. Curl command line gives 400 Tstat already connected error. HA log says the following, where the weird part to me is Transfer-Encoding: b'54\r' - what is the significance of 54?
```
This error originated from a custom integration.

Logger: custom_components.lennoxs30
Source: custom_components/lennoxs30/__init__.py:706 
Integration: Lennox S30/E30 (documentation, issues) 
First occurred: 9:17:53 PM (2 occurrences) 
Last logged: 9:18:53 PM

async_setup host [10.1.1.120] unexpected error Code [11] Reference [100] [login failed due to client response error [https://10.1.1.120/Endpoints/homeassistant/Connect] ClientResponseError Error while executing request: [Content-Length can't be present with Transfer-Encoding: b'54\r' ^]: error=<class 'aiohttp.client_exceptions.ClientResponseError'>, resp.status=[400], resp.request_info=[RequestInfo(url=URL('https://10.1.1.120/Endpoints/homeassistant/Connect'), method='POST', headers=<CIMultiDictProxy('Host': '10.1.1.120', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.11 aiohttp/3.8.5', 'Content-Length': '0', 'Content-Type': 'application/octet-stream')>, real_url=URL('https://10.1.1.120/Endpoints/homeassistant/Connect'))], resp.headers=[None]]
```

After I restarted the S40, HA Lennox integration successfully connected and my entities are sending values.

**Comment by PeteRager** [comment]
> It has to have something to do with either the Lennox cloud service or the App. I've restarted HA numerous times (> 5) and have not had a problem yet in over a week. I do not have the app installed (so I can't accidentally run it) and the S40 is blocked from anything but the local lan/HA instance.

That is a great data point.  Will edit the above note.

**Comment by 42Network** [comment]
I have updated to your 0.2.9 and the integration has survived multiple HA restarts. 

In your integration, what is the difference between Internet Status and Relay Status? Right now for my S40, Internet is Disconnected and Relay is Connected. Currently my OPNsense router is not blocking S40 access. 

Thanks.

**Comment by PeteRager** [comment]
That is good news, I will start work to make that interval configurable. So that we can vary it.  Could just be luck that it hasn't happened again, but it does seem like an improvement.

Those two sensors come directly from the S40. It sends two pieces of data "relayServerConnected" and "internetStatus".  On the S30 these are used on the panel to animate the WiFi status page.   I believe that internetStatus is determined by the s30 pinging google.com using the ICMP protocol.  The relay server status indicates if it's connected to the Lennox cloud server.   You should be able to see this connection in the states table of your firewall.

**Comment by 42Network** [comment]
I agree it could be luck, but I think I've bounced HA 4 times or so over the weekend and my S40 diag data has always remained available without required a thermostat restart. Having this wait time configurable makes sense. 

As for the internet status, does it seems strange that the thermostat can't ping Google but it is connected to Lennox cloud? I will go learn how to check FW state tables and see what I find on my router.

**Comment by PeteRager** [comment]
Yes it does seem strange.  It's also possible the S40 isn't populating / using the internetStatus field.

**Comment by 42Network** [comment]
Spoke too soon...had to restart thermostat this morning. Looks like it "crashed" about 2pm yesterday.

**Comment by PeteRager** [comment]
This did not happen during a HASS restart?  How's the WIFI strength to the thermo?

**Comment by 42Network** [comment]
No, I don't think so. WiFi strength is good - it is line-of-sight to a Unif AP on the ceiling.

**Comment by PeteRager** [comment]
Here's a draft of the current recommendations for dealing with this issue.  Feedback appreciated.

https://github.com/PeteRager/lennoxs30/blob/s40-issues-docs/docs/s40.md

As @gdoerr says - his system is reliable after deleting the app and disabling internet access.  It would be good to know if others who have this issue can get there systems setup like that to see if the issue goes away.

**Comment by 42Network** [comment]
Thanks for putting this together. Some slightly good news is that if you do
get some donations or means to purchase your own S40, the "Lennox Pro"
price is $656, plus tax and perhaps shipping, so it would be a bit less
than $1000. As a side-effect of our installation, I have access to the
lennoxpros.com site and their parts store.

Another approach might be to ask your own installer about getting upgraded
to S40, which they did for us due to dehumidification issues. I got to keep
the S30 afterwards.

Nathan Ellsworth
***@***.***
512-450-8404 cell/text

**Comment by PeteRager** [comment]
That's great @42Network, I tried to register there but I don't have an hvac license.  Check to see if they have any firmware downloads available for the S40 or S30? Do they provide support for things like my "customers" thermostat needs to be restarted every day or two 😊?

Good to know their prices are cheaper.   I'd get the S40 plus the EIM 22X18 - which allows the S40 to work with non smart equipment.  This way I could hook it up and have it do something useful - like control a ceiling fan or dehumidifier.  

The S30 has been so reliable I'm not replacing it or updating the firmware in it unless it fails.

**Comment by julietalpha1** [comment]
Lennox issued a firmware update and it appears this fixes the issue.  My 2 thermostats have remained connected to the integration after 6+ reboots of HA after having upgraded the firmware to 04.25.0070.

**Comment by PeteRager** [comment]
That is most excellent news @julietalpha1 - thanks for the update.

**Comment by TheWebMachine** [comment]
Confirmed here, too. It took an eternity to download, but I am no longer seeing the API issues. Their own app is still a little buggy, but everything in HA seems peachy keen! 

Pro tip for those attempting to update the thermostat manually: Once you initiate the update download, the Software Update page appears "broken" (only the auto updates toggle appears) because the actual download and install progress is on the Software Revision screen, instead. Took me a minute to figure that out. I thought the download was failing when the screen went to sleep. 🤦🏻‍♂️ A silly, if not confusing, design decision.

**Comment by PeteRager** [comment]
Based on the quietness of this issue, sounds like Lennox fixed the bug - THANK YOU LENNOX!!!
