### ISSUE TITLE
balancePoint question

### ISSUE THREAD

**Issue by AndrewMoscoe** [PeteRager/lennoxs30#299]
Hi,

Is the balancePoint attribute a read-only attribute or can this also be written to?

I don't yet have an S30 or Lennox HVAC system, but I am considering one, and I'd like to know if the balance point is scriptable before I get it.

**Comment by PeteRager** [comment]
Yes, all of the equipment parameters that Lennox technicians configure are accessible.  

The general documentation is here
https://github.com/PeteRager/lennoxs30/blob/master/docs/parameters.md

It does not list out all of the parameters since the list is dependent on what equipment is installed.  

There is a discuss on this topic and some people looking at doing exactly that.  They may be able to provide some examples. 

https://github.com/PeteRager/lennoxs30/discussions/297

**Comment by AndrewMoscoe** [comment]
Thank you!
