### ISSUE TITLE
Celsius has Different precision or calculation of climate temperatures

### ISSUE THREAD

**Issue by deviantintegral** [PeteRager/lennoxs30#47]
I have my themostat configured via HomeKit, but unfortunately that doesn't allow changing the themostat presets. This does! 🙌

I noticed different renderings of the temperature:

![IMG_4090](https://user-images.githubusercontent.com/255023/132432909-70d327e5-5c91-4447-88f8-cd50b7514fe6.jpg)

| Display          | Current Temperature | Low Point | High Point |
|------------------|---------------------|-----------|------------|
| Thermostat       | 23.0                | 16.5      | 23.0       |
| HomeKit Card     | 23                  | 16.5      | 23.0       |
| lennoxs30 Card   | 23                  | 17        | 23         |
| lennoxs30 Detail | 23                  | 16.7      | 22.8       |

The detail card makes me think there's some sort of rounding error and that somewhere along the way there's a Fahrenheit to Celsius conversion? Either way, I'd expect the card and detail view to be consistent, and given that the themostat indicates one tenth of a degree of precision I'd expect that to flow all the way through.

**Comment by PeteRager** [comment]
Excellent observation.   Yes, this is a problem.  The API to the Lennox Cloud sends data in both F and C.  Right now the Integration and API only get / set data in F;  so then the conversion happens in Home Assistant and those rounding errors occur.

The fix is to enable the integration to work in C or F, based on how HA is configured, then there would be no conversion in HA.  

Lennox uses whole degrees for F and increments of 0.5 for C.   Hence using a  mathematical unit conversion will create the discrepancies you see.

In this function, the C data is coming back with a C suffix.  For example hsp = heat setpoint F and hspC = heat setpoint C.  

https://github.com/PeteRager/lennoxs30api/blob/aa521c8f58cbe43a1c8e177d9c178cb019d911fc/lennoxs30api/s30api_async.py#L1076

**Comment by PeteRager** [comment]
I wrote the code today.  Next step is for me to do some basic testing.  Once that is complete I will have a build for you to do more detailed testing.   Then I am out of pocket from Sep 14 to Oct 1.  We may be able to get it done, if not it'll run over into Oct.

**Comment by PeteRager** [comment]
This actually went alot faster than I was expecting.

Give this branch a try.  It will detect your HA system is configured in metric and report data in Celsius.  In lennox all celsius is in 0.5 degree increments.  The climate card should also increment in 0.5 degrees for setpoint.

It should automatically pull the update API version 0.0.8 (which also has that log.info reduction).  I have tested celsius mode on my LennoxS30; but I only have a cooling system so I have not been able to validate the heat-setpoints.  If you have an outdoor temperature sensor that should also be now natively in celsius.

https://github.com/PeteRager/lennoxs30/tree/0.0.9

Create issues for any bugs you find and let me know when you've completed testing.  Once we get through that, I'll publish this as a release.

**Comment by deviantintegral** [comment]
First pass, everything looks good. I was able to change a heat setpoint. I don't have an outdoor temperature sensor. There is some interesting back-and-forth when I change setpoints, but I'm guessing that's an API issue. It does settle after 5 seconds or so.

**Comment by PeteRager** [comment]
Sounds good.  Thanks for testing. 

On the setpoint back and forth, that’s in the Lovelace card?  Here’s why that is.

1. Change setpoint in card
2. Card calls integration with requested setpoint
3. Integration call Lennox Cloud API and returns

then in the background this happens

4. Lennox Cloud API sends request to thermostat
5. Thermostat processes request and updates actual setpoint
6. Thermostat sends new setpoint to cloud
7. Integration is polling (using fast poll interval) and gets update
8. State is updated in HA
9. State is updated in Card

That whole process takes time.  I’ve seen it take up to 30 seconds.  But 5-10 is more typical. 

The card “holds” the requested setpoint for a time (couple of seconds) before reverting to the current set point.  Hence I think what you are seeing is that reversion because steps 4-9 are still in progress?

I don’t think the integration should updates the setpoint state until it’s really happened in the thermostat, otherwise we could get in a situation where an unreported failure in steps 4-9 causes HA to have the wrong data.  It could be possible to allow the card hold time to be configurable.

**Comment by deviantintegral** [comment]
Yes, I'm sure that's the case. In truth, I think this is a larger issue with Home Assistant's UI. As far as I know, it has no "pending change" or "in progress" UI for services that take time to respond. In an ideal world, there'd be some affordance to let users know on any card that an action is underway.

**Comment by PeteRager** [comment]
Agreed.  Either way, I’ll close this issue since it’s resolved and publish that branch as a new release.  If you encounter new issues or see enhancement opportunities please open an issue.
