### ISSUE TITLE
Range selection for cool only

### ISSUE THREAD

**Issue by dresslerc** [PeteRager/lennoxs30#49]
I have my Lennox app set to cool only, but I’m HA I see 3 temperatures.  Looks like a range selection and something else?  Not sure how to fully explain it, but see pictures below.  

In my case, I have 2 zones. 

![457FB10C-6554-44F3-9A99-92032DC3DEE3](https://user-images.githubusercontent.com/375080/134265260-1f2c36cd-2b42-4f80-9239-0324265394ff.jpeg)
![778957CA-E9C8-43B5-B79E-E1419055137C](https://user-images.githubusercontent.com/375080/134265265-61769b11-ca2b-4fe9-99ce-60d47bf077b5.jpeg)
![6D827CEA-E5AD-4269-863E-AB7183975BBA](https://user-images.githubusercontent.com/375080/134265269-66150c6f-1898-4aaa-8216-2fe74aa5cbeb.png)

**Comment by PeteRager** [comment]
The lower temperature is your heat set point.  71 and 64 respectively.  If your system was in heat-cool mode Heat would come on at those temperatures. However since it’s in Cool mode Heat will not come on.  Ideally the thermostat card would not show both but it does.

Hope that answers your question. I’m away for a bit responses may be delayed.

**Comment by PeteRager** [comment]
Let me know if that answered your question.

**Comment by PeteRager** [comment]
After further review, this is a bug and is being fixed, should be available later this week.

**Comment by dresslerc** [comment]
Once ready I can test

**Comment by PeteRager** [comment]
Resolved in upcoming 0.1.2 release

**Comment by PeteRager** [comment]
Prerelease here - https://github.com/PeteRager/lennoxs30/releases/tag/v0.1.2

**Comment by PeteRager** [comment]
Closing for now, open a new issue if you see problems
