### ISSUE TITLE
Create an energy sensor to represent HVAC power usage

### ISSUE THREAD

**Issue by hufman** [PeteRager/lennoxs30#70]
As part of the local API, clients can request advanced diagnostic data from the HVAC controller, and one of the data points includes energy usage of the compressor. With the new Energy dashboard in recent Home Assistant versions, it would be nifty to enable the HVAC system to show up in the energy usage dashboard.

I believe it will involve the following work:

- [x] Adding a config option to configure lennoxs30api to enable diagnostic mode
- [x] Parsing the diagnostics data to save the current power information
- [x] Building a new DEVICE_CLASS_POWER entity to provide that information to Home Assistant
- [x] Documenting the [integration](https://www.home-assistant.io/integrations/integration/) configuration to convert this power information to the Total KWh Used, which can then be added to the Energy Dashboard

**Comment by hufman** [comment]
Here's an Equipments report (with some unnecessary information removed) showing where in the data structure you can find the `Inverter Input Voltage` and `Inverter Input Current` values.
[equipments-diag.zip](https://github.com/PeteRager/lennoxs30/files/7457045/equipments-diag.zip)

**Comment by PeteRager** [comment]
Some considerations:

- [ ] Add ability for API to capture and report current diagnostic state, add this as an attribute to the climate object
- [ ] Determine what diagnostic level is needed to get this information.  I think we know that at level 0 it does not, and at Level 2 it does, what about level 1?
- [ ] As diagnostic data streams in, evaluate if messages are causing unneeded entity updates

**Comment by HyperActiveJ** [comment]
I just did this in my 'proof of concept' component since I had that data already and could do a quick P=IV. It seems to work, unclear on measurement accuracy... Also looks like the inverter input current on mine is reporting bogus when compressor is not running - its always reporting a >0.2A @240V= 48W. Pulling he breaker and watching the power meter doesn't appear to shore more then 12W delta, but it could be noise or inaccuracy in my measurement.  Might need more investigation. The compressor current combined with the DC link voltage was also interesting...

Is anyone working this issue?  If not I'd be happy to have a go at it.  If i do, id like to also (if you think its appropriate):
1. Create a HA Device entity associated with the HVAC (Optional, spilt into Furnace, Condenser, Control Head devices) to encompass the entities. 
2. Add additional sensors for some the what is currently exported as 'attributes'


SensorEntityDescription(
        key="LennoxHTTPS_Diagnostic_1_11_Inverter Input Voltage",
        name="Inverter Input Voltage",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        device_class=DEVICE_CLASS_VOLTAGE,
),
SensorEntityDescription(
        key="LennoxHTTPS_Diagnostic_1_12_Inverter Input Current",
        name="Inverter Input Current",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        device_class=DEVICE_CLASS_CURRENT,
),
SensorEntityDescription(
        key="LennoxHTTPS_Diagnostic_1_13_DC Link Voltage",
        name="DC Link Voltage",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        state_class=STATE_CLASS_MEASUREMENT,
        device_class=DEVICE_CLASS_VOLTAGE,
),
SensorEntityDescription(
        key="LennoxHTTPS_Diagnostic_1_14_Compressor Current",
        name="Compressor Current",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        state_class=STATE_CLASS_MEASUREMENT,
        device_class=DEVICE_CLASS_CURRENT,
),

**Comment by hufman** [comment]
It's interesting to see that your system has the diagnostics at different IDs! Mine are [around id 19](https://github.com/PeteRager/lennoxs30api/pull/23/files#diff-6013141c8d6484cbc4ef32301b22f8fca8855a3e2bcfbd1e72919c48c3a53c60R189).
I drafted up a rough power sensor at #79 for review! I see the same thing you see, where my inverter apparently idles at 75w... It'll be important to find the balance between detailed diagnostics information and useful information, so this sensor implementation only emits the calculated power instead of the separate voltage and current.

**Comment by HyperActiveJ** [comment]
Interesting, hmm I was just browsing the test code and example response json you attached to the api pull request. There are some deltas between our systems responces..... will have to make some time to see if it works as is. 

I temporarily rewrote sensor.py in my local brach to automatically add all reported information from the api, rather then hard coding each sensor (outdoor temp, indor humidity, power, etc). It's actually wayyy shorter this way. That way I can play in the api without having to visit the home assistant integration or component or what ever this is called. I then changed the api to discover the sensors as it gets messages and report them to home assistant for obhect creation. Right how it reports probably to many things and not always the right device type, but that's ok with me. Reason I bring it up is that I'm guessing we're going to have lots of variation between cooling only systems, heat pumps, furnace only systems, different number of stages and boosts, etc. The only way to support them all and stay sane as developed might be to stick to this automated method. All the info needed is right there in the responces. 

Thoughts?

Ttests/messages/equipments_response_energy.json

**Comment by PeteRager** [comment]
> It's interesting to see that your system has the diagnostics at different IDs! Mine are [around id 19](https://github.com/PeteRager/lennoxs30api/pull/23/files#diff-6013141c8d6484cbc4ef32301b22f8fca8855a3e2bcfbd1e72919c48c3a53c60R189).
> I drafted up a rough power sensor at #79 for review! I see the same thing you see, where my inverter apparently idles at 75w... It'll be important to find the balance between detailed diagnostics information and useful information, so this sensor implementation only emits the calculated power instead of the separate voltage and current.

That’s a good discovery.   Name matching it is and there is no separate “fid” like on some other data.

This articles explains inverters (new to me), does say they often idle at a low setting vs going off.

https://www.pickhvac.com/faq/air-conditioner-inverter-the-secret-to-skyrocket-your-efficiency/

Putting a CT clamp on the circuits may help determine if it’s using 75w or not. On my system AC only, there are two circuits - one for the compressor and one for the air handler.  After reading the article, the inverter is the compressor.  Do we see anything for the air handler also?

Do we know what the inverter is electronically / physically in the system?

**Comment by HyperActiveJ** [comment]
It looks like we're not accounting for power factor and reporting apparent power instead of true power, which is why there is a decreasing delta as true load increases. I don't see a way to detrimine power factor in real time. Best thought I have would be to measure it with a meter and hard code a calibration table l.

**Comment by HyperActiveJ** [comment]
Or use compressor dc voltage x compressor dc current measures instead

**Comment by hufman** [comment]
That's interesting, I hadn't considered the power factor aspect.
My system has a Compressor Current, but I'm not sure which voltage it would be multiplied with. The only other voltage that looks reasonable is the Line Voltage (currently 593V). I don't think it would the 24VAC Voltage (currently 28V) or the DC Link Voltage (currently 6V). Does your system have a specific Compressor Voltage data point?

**Comment by HyperActiveJ** [comment]
In think it's line voltage and I miss typed. When you multiply line voltage
times compressor current does it seem reasonable? The other value of
interest would be compressor frequency. Doing this wouldn't account for
inverter efficiency losses, so there doesn't seem to be a stand out perfect
answer there either.

In the device data there is also a "Max power" and some other powers
reported, oddly I think including 24v power of all things if I recall
correctly, I don't have a copy of my logs on hand. Might be worth
looking into those out of curiosity.

**Comment by HyperActiveJ** [comment]
Edit: it's also in diagnostics data under "features" and is per equipment
type - looks like one set for furnace and one for condenser

Names:
Line voltage avg. power consumption
Line voltage peak power consumption
And corresponding 24vac equivalent

**Comment by PeteRager** [comment]
We will see variation based on what equipment is installed.  For example a non variable speed compressor will not have an inverter.   The first goal should be to have it work for the equipment we have in hand.  As other users pick it up and say - hey this isn’t working with my heat pump - we can address those as enhancements - add there JSON to our tests/messages for reference and unit testing.

A key question is can the S30 be stable when in diagLevel 2 for a sustained period of time?  Having the HVAC controller reboot is not ideal since the HVAC system probably not able to run during this time.  Systems don’t always fail / handle failures consistently - so a hang, or failure to reboot could result in no HVAC.

**Comment by hufman** [comment]
As of this morning, it seems like my system has been running in diagnostic mode and staying alive for 230 hours.

**Comment by PeteRager** [comment]
> As of this morning, it seems like my system has been running in diagnostic mode and staying alive for 230 hours.
> 

That’s excellent news.  My system in non diag has been rock solid for 1,000,000 seconds.  Today the cloud connection has be very flaky getting 502s and messages are getting dropped on each 502 ☹️

**Comment by PeteRager** [comment]
Going to punch out a release next week as there’s some fixes folks are waiting for.  Let me know if there are other elements on this issue that we want / have time to include.

**Comment by PeteRager** [comment]
In this release and should now work.  Open a new issue if there are issues.

https://github.com/PeteRager/lennoxs30/releases/tag/v0.1.3a
