### ISSUE TITLE
Away Mode

### ISSUE THREAD

**Issue by PeteRager** [PeteRager/lennoxs30#9]
Turn away mode on and off.

**Comment by rob51i03** [comment]
This would be a great enhancement! Thanks for working on this... leaving a note so I get notified of updates.

**Comment by PeteRager** [comment]
Is the behavior needed the same as clicking the little green away icon in the upper left hand corner?

**Comment by PeteRager** [comment]
This message is sent when turning on away mode

{"MessageType":"Command","SenderID":"mapp67306035441582313397_myemail@email.com","MessageID":"00000000-0000-0000-0000-000000000001","TargetID":"00000","Data":{"occupancy":{"manualAway":true}}}

Then this status update happens

"Data":{"occupancy":{"manualAway":true,"publisher":{"publisherName":"remote"}}},

{"MessageType":"Command","SenderID":"mapp67306035441582313397_myemail@email.com","MessageID":"00000000-0000-0000-0000-000000000002","TargetID":"000000","Data":{"occupancy":{"manualAway":false}}}

"Data":{"occupancy":{"manualAway":false,"publisher":{"publisherName":"remote"}}},"AdditionalParameters":null}]

**Comment by PeteRager** [comment]
A question on behaviors.  In Lennox when away mode is removed the zone returns to whatever is was doing before.

In HA, the AWAY preset is used; and in order to remove AWAY mode a different preset must be selected.  So that behavior will be supported.  In addition adding a "CANCEL_AWAY" preset; will allow the zone to return to whatever it was doing before.  I will add that to.

Comments?

**Comment by rob51i03** [comment]
> A question on behaviors. In Lennox when away mode is removed the zone returns to whatever is was doing before.
> 
> In HA, the AWAY preset is used; and in order to remove AWAY mode a different preset must be selected. So that behavior will be supported. In addition adding a "CANCEL_AWAY" preset; will allow the zone to return to whatever it was doing before. I will add that to.
> 
> Comments?

Being able to do both is great. I really like the CANCEL_AWAY idea, it makes automating the resume to normal running super easy. That said, I've already implemented logic to pick the right seasonal program (I have the S30 turn off if a window is open more than a few minutes, and resume according to season when the windows are closed again) so for me either would work.

**Comment by PeteRager** [comment]
Sounds good and thanks for the feedback.  I have the code written, need to test, should have something out for you to look at by end of next week.

**Comment by PeteRager** [comment]
@rob51i03 - take a look at this for your other issue - have some questions on how it should work. Thanks 

https://github.com/PeteRager/lennoxs30/issues/36

**Comment by Smoot178** [comment]
Looking for this feature as well.  Happy to test.

**Comment by PeteRager** [comment]
Sounds good, I have the code now working.  A little more testing, then I'll create a release package for you to try.

**Comment by PeteRager** [comment]
I published release 0.0.7 - https://github.com/PeteRager/lennoxs30/releases/tag/v0.0.7

Please download and give a test.  Note, on my first startup Lennox servers did not respond well, the integration handled the error and retried a minute later which did work.  Anyways, you may see that also :-(.

There are two new presets - "Away"  and "cancel away mode" - the first puts the system into away mode, the second cancels away mode and the system should return to whatever state it was in before away mode was set.    Functionally, it should be identical to using the away mode button on the S30 panel.

Let me know how it goes and create issues if you see issues!

**Comment by PeteRager** [comment]
Please use this release - https://github.com/PeteRager/lennoxs30/releases/tag/v0.0.8

There is a nasty reconnect bug in version 0.0.7 (and all prior versions)

**Comment by rob51i03** [comment]
Presets "away" and "cancel away mode" are both working great! Everything else seems to be okay after upgrading to 0.0.8 too. Thumbs-up from me. Thanks!
On 2021-08-06 9:02:03 PM, PeteRager ***@***.***> wrote:
Please use this release - https://github.com/PeteRager/lennoxs30/releases/tag/v0.0.8 [https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPeteRager%2Flennoxs30%2Freleases%2Ftag%2Fv0.0.8&amp;data=04%7C01%7C%7C19802993762640b1877008d9593ef7a4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638949234688493%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=0LhitrzBrO0%2FRxJ8mye4uA3SJHRJ4eYeEdCmhGEBHIA%3D&amp;reserved=0]
There is a nasty reconnect bug in version 0.0.7 (and all prior versions)
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPeteRager%2Flennoxs30%2Fissues%2F9%23issuecomment-894581838&amp;data=04%7C01%7C%7C19802993762640b1877008d9593ef7a4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638949234688493%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=T9VeGTLMfkHXKsqQZX5RxeSguCrEVppJeIE3TbrW6QA%3D&amp;reserved=0], or unsubscribe [https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGBVZVRFQOV7QUVHLQW2BK3T3SAYVANCNFSM46EQOIWQ&amp;data=04%7C01%7C%7C19802993762640b1877008d9593ef7a4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638949234698454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=itok7v7XC3q9rqQEzAHl78JE%2BY2e4IV5os2Ad2DfOO0%3D&amp;reserved=0].
Triage notifications on the go with GitHub Mobile for iOS [https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&amp;data=04%7C01%7C%7C19802993762640b1877008d9593ef7a4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638949234698454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=HGOY9CNw2DAOimRY%2Bh5tYhS%2BlybA8kerKBzYXC5aVNM%3D&amp;reserved=0] or Android [https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&amp;data=04%7C01%7C%7C19802993762640b1877008d9593ef7a4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637638949234708410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=8%2FBrL9SPFj9z0TF1D%2Fmm1EXURX1ZpV7UDBXksDJvKks%3D&amp;reserved=0].

**Comment by rob51i03** [comment]
~~Presets "away" and "cancel away mode" are both working great! Everything else seems to be okay after upgrading to 0.0.8 too. Thumbs-up from me. Thanks!~~

Spoke too soon. Unpredictable behaviour since the upgrade, affecting all changes in S20 state issued by HA. New issue raised.
